version: "3.7"

services:
    database:
        container_name: mariadb
        image: mariadb:10.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: 1234
            MYSQL_USER: aziz
            MYSQL_DATABASE: smartphone